blank_issues_enabled: false
contact_links:
  - name: Request a new feature
    url: https://github.com/diego-ninja/cartographer/issues/new?labels=enhancement
    about: Share ideas for new features / functions
  - name: Report a bug
    url: https://github.com/diego-ninja/cartographer/issues/new?labels=bug
    about: Report a reproducible bug
  - name: Documentation
    url: https://github.com/diego-ninja/cartographer/issues/new?labels=documentation
    about: Improvements or additions to documentation
